server:
  port: 8999
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/route?characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.big_cat.generator.model
##  逻辑删除配置
#  global-config:
#    enable-sql-runner: true
